SCAN: App\Http\Controllers\FieldsController Class Reference
App\Http\Controllers\FieldsController Class Reference
Public Member Functions
__construct ()
index ()
store (StoreFieldRequest $request)
create ()
show (Field $field)
edit (Field $field)
destroy (Field $field)
handleApiRequest (Request $request)
update (UpdateFieldRequest $request, Field $field)
Detailed Description
Definition at line 20 of file FieldsController.php.
Constructor & Destructor Documentation
__construct()
App\Http\Controllers\FieldsController::__construct ()
Create the controller instance.
Returns
void
Definition at line 27 of file FieldsController.php.
Member Function Documentation
create()
App\Http\Controllers\FieldsController::create ()
Show the form for creating a new resource.
Returns
View
Definition at line 102 of file FieldsController.php.
destroy()
App\Http\Controllers\FieldsController::destroy (Field $field)
Remove the specified resource from storage.
Parameters
Field $field
Returns
RedirectResponse
Definition at line 179 of file FieldsController.php.
edit()
App\Http\Controllers\FieldsController::edit (Field $field)
Show the form for editing the specified resource.
Parameters
Field $field
Returns
View
Definition at line 137 of file FieldsController.php.
References App\Models\Field\getLinkedListId(), App\Models\Field\getRequiredId(), and App\Models\Field\getStatusId().
handleApiRequest()
App\Http\Controllers\FieldsController::handleApiRequest (Request $request)
Returns a json which contains all the fields
Parameters
Request $request
Definition at line 189 of file FieldsController.php.
References $log.
index()
App\Http\Controllers\FieldsController::index ()
Display a listing of the resource.
Returns
View
Definition at line 37 of file FieldsController.php.
show()
App\Http\Controllers\FieldsController::show (Field $field)
Display the specified resource.
Parameters
Field $field
Returns
View
Definition at line 113 of file FieldsController.php.
References App\Models\Field\dataType().
store()
App\Http\Controllers\FieldsController::store (StoreFieldRequest $request)
Store a newly created resource in storage.
Parameters
StoreFieldRequest $request
Returns
RedirectResponse
Definition at line 47 of file FieldsController.php.
update()
App\Http\Controllers\FieldsController::update (UpdateFieldRequest $request, Field $field)
Update the specified resource in storage.
Parameters
UpdateFieldRequest $request
Field $field
Returns
RedirectResponse
Definition at line 226 of file FieldsController.php.
The documentation for this class was generated from the following file:
src/app/Http/Controllers/FieldsController.php