SCAN: App\Actions\Jetstream\InviteTeamMember Class Reference
App\Actions\Jetstream\InviteTeamMember Class Reference
Public Member Functions
invite ($user, $team, string $email, string $role=null)
Protected Member Functions
validate ($team, string $email, ?string $role)
rules ($team)
ensureUserIsNotAlreadyOnTeam ($team, string $email)
Detailed Description
Definition at line 15 of file InviteTeamMember.php.
Member Function Documentation
ensureUserIsNotAlreadyOnTeam()
App\Actions\Jetstream\InviteTeamMember::ensureUserIsNotAlreadyOnTeam ($team, string $email) protected
Ensure that the user is not already on the team.
Parameters
mixed $team
string $email
Returns
\Closure
Definition at line 87 of file InviteTeamMember.php.
Referenced by App\Actions\Jetstream\InviteTeamMember\validate().
invite()
App\Actions\Jetstream\InviteTeamMember::invite ($user, $team, string $email, string $role = null)
Invite a new team member to the given team.
Parameters
mixed $user
mixed $team
string $email
string | null $role
Returns
void
Definition at line 26 of file InviteTeamMember.php.
References App\Actions\Jetstream\InviteTeamMember\validate().
rules()
App\Actions\Jetstream\InviteTeamMember::rules ($team) protected
Get the validation rules for inviting a team member.
Parameters
mixed $team
Returns
array
Definition at line 68 of file InviteTeamMember.php.
Referenced by App\Actions\Jetstream\InviteTeamMember\validate().
validate()
App\Actions\Jetstream\InviteTeamMember::validate ($team, string $email, ?string $role) protected
Validate the invite member operation.
Parameters
mixed $team
string $email
string | null $role
Returns
void
Definition at line 50 of file InviteTeamMember.php.
References App\Actions\Jetstream\InviteTeamMember\ensureUserIsNotAlreadyOnTeam(), and App\Actions\Jetstream\InviteTeamMember\rules().
Referenced by App\Actions\Jetstream\InviteTeamMember\invite().
The documentation for this class was generated from the following file:
src/app/Actions/Jetstream/InviteTeamMember.php