SCAN: App\Models\Role Class Reference
App\Models\Role Class Reference
Public Member Functions
users ()
permissions ()
Static Public Member Functions
static biggestRole ()
static smallestRole ()
static getRouteBases ()
static getSortedPermisisons ($route_bases)
Public Attributes
$incrementing = false
Protected Attributes
$keyType = 'string'
$guarded = []
$hidden = ['deleted_at', "created_at", "updated_at"]
Detailed Description
Definition at line 11 of file Role.php.
Member Function Documentation
biggestRole()
static App\Models\Role::biggestRole () static
Definition at line 49 of file Role.php.
Referenced by App\Models\User\genRole().
getRouteBases()
static App\Models\Role::getRouteBases () static
Definition at line 75 of file Role.php.
getSortedPermisisons()
static App\Models\Role::getSortedPermisisons ($route_bases) static
Definition at line 87 of file Role.php.
permissions()
App\Models\Role::permissions ()
The permissions that belong to the user.
Definition at line 70 of file Role.php.
Referenced by App\Http\Controllers\RoleController\update().
smallestRole()
static App\Models\Role::smallestRole () static
Definition at line 54 of file Role.php.
Referenced by App\Models\User\genRole().
users()
App\Models\Role::users ()
Definition at line 45 of file Role.php.
Member Data Documentation
$guarded
App\Models\Role::$guarded = [] protected
Definition at line 36 of file Role.php.
$hidden
App\Models\Role::$hidden = ['deleted_at', "created_at", "updated_at"] protected
Definition at line 43 of file Role.php.
$incrementing
App\Models\Role::$incrementing = false
Definition at line 28 of file Role.php.
$keyType
App\Models\Role::$keyType = 'string' protected
Definition at line 20 of file Role.php.
The documentation for this class was generated from the following file:
src/app/Models/Role.php