SCAN: App\Http\Controllers\RefugeeController Class Reference
App\Http\Controllers\RefugeeController Class Reference
Public Member Functions
__construct ()
update (UpdateRefugeeRequest $request, Refugee $person)
index ()
show (Refugee $person)
createFromJson ()
store (StoreRefugeeRequest $request)
create ()
edit (Refugee $person)
fixDuplicatedReference (Request $request, $refugee_id)
destroy (Refugee $person)
import (FileRefugeeRequest $request)
storeFromJson (Request $request)
Static Public Member Functions
static apiGetPerson (Request $request, Crew $crew=null)
static handleApiRequest (StoreRefugeeApiRequest $request)
Detailed Description
Definition at line 28 of file RefugeeController.php.
Constructor & Destructor Documentation
__construct()
App\Http\Controllers\RefugeeController::__construct ()
Create the controller instance.
Returns
void
Definition at line 35 of file RefugeeController.php.
Member Function Documentation
apiGetPerson()
static App\Http\Controllers\RefugeeController::apiGetPerson (Request $request, Crew $crew = null) static
This function is used to return the get person API request. It should be used only by the API. It returns the list of all the person for a given crew. By default, the crew of the user, if a crew id is given, it will return the person of the given crew. It never returns the person that are not in the given crew. The person must have get permission to be returned.
Parameters
Request $request
Crew $crew
Returns
Response
Definition at line 51 of file RefugeeController.php.
References $log.
create()
App\Http\Controllers\RefugeeController::create ()
Show the form for creating a new resource.
Returns
View
Definition at line 251 of file RefugeeController.php.
createFromJson()
App\Http\Controllers\RefugeeController::createFromJson ()
Show the form for creating a new resource from a json file.
Returns
View
Definition at line 206 of file RefugeeController.php.
destroy()
App\Http\Controllers\RefugeeController::destroy (Refugee $person)
Remove the specified resource from storage.
Parameters
Refugee $person
Returns
RedirectResponse
Definition at line 308 of file RefugeeController.php.
edit()
App\Http\Controllers\RefugeeController::edit (Refugee $person)
Show the form for editing the specified resource.
Parameters
Refugee $person
Returns
View
Definition at line 268 of file RefugeeController.php.
References App\Models\Refugee\fields().
fixDuplicatedReference()
App\Http\Controllers\RefugeeController::fixDuplicatedReference (Request $request, $refugee_id)
Update the specified resource in storage.
Parameters
Request $request
String $refugee_id
Returns
RedirectResponse
Definition at line 293 of file RefugeeController.php.
handleApiRequest()
static App\Http\Controllers\RefugeeController::handleApiRequest (StoreRefugeeApiRequest $request) static
Handle the API request
Parameters
StoreRefugeeApiRequest $request
Returns
Response
Definition at line 370 of file RefugeeController.php.
References $log.
import()
App\Http\Controllers\RefugeeController::import (FileRefugeeRequest $request)
Definition at line 318 of file RefugeeController.php.
References App\Http\Controllers\RefugeeController\storeFromJson().
index()
App\Http\Controllers\RefugeeController::index ()
Display a listing of the resource.
Returns
View
Definition at line 137 of file RefugeeController.php.
show()
App\Http\Controllers\RefugeeController::show (Refugee $person)
Display the specified resource.
Parameters
Refugee $person
Returns
View
Definition at line 157 of file RefugeeController.php.
References App\Models\Refugee\allCoordinates().
store()
App\Http\Controllers\RefugeeController::store (StoreRefugeeRequest $request)
Store a newly created resource in storage.
Parameters
StoreRefugeeRequest $request
Returns
RedirectResponse
Definition at line 216 of file RefugeeController.php.
References $log.
storeFromJson()
App\Http\Controllers\RefugeeController::storeFromJson (Request $request)
Store a newly created resource from json file in storage.
Parameters
JsonFileRefugeeRequest $request
Returns
RedirectResponse
Definition at line 343 of file RefugeeController.php.
References $log.
Referenced by App\Http\Controllers\RefugeeController\import().
update()
App\Http\Controllers\RefugeeController::update (UpdateRefugeeRequest $request, Refugee $person)
Update the specified resource in storage.
Parameters
UpdateRefugeeRequest $request
Refugee $person
Returns
RedirectResponse
Definition at line 80 of file RefugeeController.php.
References $log, and App\Models\Refugee\fields().
The documentation for this class was generated from the following file:
src/app/Http/Controllers/RefugeeController.php