SCAN: App\Models\User Class Reference
App\Models\User Class Reference
Public Member Functions
genToken ($default=false)
getToken ()
genRole ()
crew ()
role ()
roleRequest ()
Static Public Member Functions
static createDefaultUser ()
Public Attributes
$incrementing = false
Protected Attributes
$keyType = 'string'
$fillable
$hidden
$casts
$encryptable
Detailed Description
Definition at line 17 of file User.php.
Member Function Documentation
createDefaultUser()
static App\Models\User::createDefaultUser () static
Create the default user
Definition at line 87 of file User.php.
References App\Models\Crew\getDefaultCrewId().
crew()
App\Models\User::crew ()
Definition at line 158 of file User.php.
Referenced by App\Policies\RefugeePolicy\create(), App\Policies\RefugeePolicy\createFromJson(), and App\Models\Field\getAPIContent().
genRole()
App\Models\User::genRole ()
Generate a role by default
Definition at line 144 of file User.php.
References App\Models\Role\biggestRole(), App\Models\User\role(), and App\Models\Role\smallestRole().
Referenced by App\Actions\Fortify\CreateNewUser\create().
genToken()
App\Models\User::genToken ($default = false)
Create a personal Token API.
Returns
void
Definition at line 103 of file User.php.
References App\Models\User\getToken().
Referenced by App\Actions\Fortify\CreateNewUser\create().
getToken()
App\Models\User::getToken ()
Return an API token
Returns
string|string[]|null
Definition at line 129 of file User.php.
Referenced by App\Models\User\genToken().
role()
App\Models\User::role ()
Definition at line 162 of file User.php.
Referenced by App\Models\User\genRole().
roleRequest()
App\Models\User::roleRequest ()
Definition at line 166 of file User.php.
Member Data Documentation
$casts
App\Models\User::$casts protected
Initial value:
= [
        'email_verified_at' => 'datetime',
    ]
Definition at line 70 of file User.php.
$encryptable
App\Models\User::$encryptable protected
Initial value:
= [
         'name'
    ]
Definition at line 79 of file User.php.
$fillable
App\Models\User::$fillable protected
Initial value:
= [
        'name', 'email',
        'password', "token",
        "role_id", "crew_id",
    ]
Definition at line 46 of file User.php.
$hidden
App\Models\User::$hidden protected
Initial value:
= [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
        'token',
    ]
Definition at line 57 of file User.php.
$incrementing
App\Models\User::$incrementing = false
Definition at line 34 of file User.php.
$keyType
App\Models\User::$keyType = 'string' protected
Definition at line 40 of file User.php.
The documentation for this class was generated from the following file:
src/app/Models/User.php