SCAN: App\Models\Field Class Reference
App\Models\Field Class Reference
Public Member Functions
getStatusAttribute ($value)
getStatusId ()
getRequiredAttribute ($value)
getRequiredId ()
getValue ()
linkedList ()
getLinkedListContent ()
getLinkedListId ()
listControl ()
dataType ()
Static Public Member Functions
static getUsedLinkedList ()
static getAPIContent (User $user)
static convertRequiredAttribute ($value)
static hasBestDescriptiveValue ()
Public Attributes
$incrementing = false
Static Public Attributes
static $requiredTypes
static $statusTypes
Protected Attributes
$keyType = 'string'
$guarded = []
$hidden = ['deleted_at', "created_at", "updated_at", "status", "html_data_type", "validation_laravel", "attribute", "order", "api_log", "crew_id"]
$encryptable
Detailed Description
Definition at line 13 of file Field.php.
Member Function Documentation
convertRequiredAttribute()
static App\Models\Field::convertRequiredAttribute ($value) static
Convert a given requirement description into the associate int
Parameters
$value
Returns
int
Definition at line 117 of file Field.php.
Referenced by App\Models\Field\getAPIContent().
dataType()
App\Models\Field::dataType ()
Field hasOne data type
Definition at line 275 of file Field.php.
Referenced by App\Models\Field\getValue(), and App\Http\Controllers\FieldsController\show().
getAPIContent()
static App\Models\Field::getAPIContent (User $user) static
It returns the list control dataset for API calls
Returns
array
Definition at line 87 of file Field.php.
References App\Models\Field\convertRequiredAttribute(), and App\Models\User\crew().
getLinkedListContent()
App\Models\Field::getLinkedListContent ()
Get all the element from the linkedlist
Parameters
string $id
Returns
array
Definition at line 249 of file Field.php.
References App\Models\Field\getLinkedListId().
getLinkedListId()
App\Models\Field::getLinkedListId ()
Indicate the the UUID stored in DB
Returns
String
Definition at line 262 of file Field.php.
Referenced by App\Http\Controllers\FieldsController\edit(), and App\Models\Field\getLinkedListContent().
getRequiredAttribute()
App\Models\Field::getRequiredAttribute ($value)
Definition at line 190 of file Field.php.
getRequiredId()
App\Models\Field::getRequiredId ()
Indicate the the required id stored in DB
Returns
String
Definition at line 218 of file Field.php.
Referenced by App\Http\Controllers\FieldsController\edit().
getStatusAttribute()
App\Models\Field::getStatusAttribute ($value)
Definition at line 148 of file Field.php.
getStatusId()
App\Models\Field::getStatusId ()
Getter to return correctly the linkedlist name
Parameters
$value
Returns
string Indicate the the status id stored in DB
String
Definition at line 185 of file Field.php.
Referenced by App\Http\Controllers\FieldsController\edit().
getUsedLinkedList()
static App\Models\Field::getUsedLinkedList () static
Definition at line 75 of file Field.php.
getValue()
App\Models\Field::getValue ()
Definition at line 222 of file Field.php.
References App\Models\Field\dataType(), and App\Models\Field\linkedList().
hasBestDescriptiveValue()
static App\Models\Field::hasBestDescriptiveValue () static
This function returns true if the best_descriptive_value is defined, false otherwise
Returns
bool
Definition at line 144 of file Field.php.
linkedList()
App\Models\Field::linkedList ()
Definition at line 239 of file Field.php.
Referenced by App\Models\Field\getValue().
listControl()
App\Models\Field::listControl ()
Definition at line 267 of file Field.php.
Member Data Documentation
$encryptable
App\Models\Field::$encryptable protected
Initial value:
= [
        'title', 'label', 'placeholder'
    ]
Definition at line 71 of file Field.php.
$guarded
App\Models\Field::$guarded = [] protected
Definition at line 57 of file Field.php.
$hidden
App\Models\Field::$hidden = ['deleted_at', "created_at", "updated_at", "status", "html_data_type", "validation_laravel", "attribute", "order", "api_log", "crew_id"] protected
Definition at line 64 of file Field.php.
$incrementing
App\Models\Field::$incrementing = false
Definition at line 45 of file Field.php.
$keyType
App\Models\Field::$keyType = 'string' protected
Definition at line 51 of file Field.php.
$requiredTypes
App\Models\Field::$requiredTypes static
Initial value:
= [
        2 => "Strongly advised",
        3 => "Advised",
        4 => "If possible",
        100 => "Undefined"
    ]
Definition at line 22 of file Field.php.
$statusTypes
App\Models\Field::$statusTypes static
Initial value:
= [
        0 => "Disabled",
        1 => "Website",
        2 => "Website & App"
    ]
Definition at line 34 of file Field.php.
The documentation for this class was generated from the following file:
src/app/Models/Field.php