SCAN: App\Actions\Fortify\CreateNewUser Class Reference
App\Actions\Fortify\CreateNewUser Class Reference
Public Member Functions
create (array $input)
Protected Member Functions
createTeam (User $user)
Detailed Description
Definition at line 14 of file CreateNewUser.php.
Member Function Documentation
create()
App\Actions\Fortify\CreateNewUser::create (array $input)
Create a newly registered user.
Parameters
array $input
Returns
\App\Models\User
Definition at line 24 of file CreateNewUser.php.
References App\Actions\Fortify\CreateNewUser\createTeam(), App\Models\User\genRole(), and App\Models\User\genToken().
createTeam()
App\Actions\Fortify\CreateNewUser::createTeam (User $user) protected
Create a personal team for the user.
Parameters
\App\Models\User $user
Returns
void
Definition at line 52 of file CreateNewUser.php.
Referenced by App\Actions\Fortify\CreateNewUser\create().
The documentation for this class was generated from the following file:
src/app/Actions/Fortify/CreateNewUser.php