SCAN: App\Policies\GlobalPolicy Class Reference
App\Policies\GlobalPolicy Class Reference
Public Member Functions
__construct ($route_name)
viewAny (User $user)
hasPermission ($user, $function)
viewMenu (User $user)
view (User $user, Model $model)
create (User $user)
createFromJson (User $user)
update (User $user, Model $model)
delete (User $user, Model $model)
restore (User $user, Model $model)
forceDelete (User $user, Model $model)
Public Attributes
const ERROR_MESSAGE = 'You do not have the right to do this.'
Protected Attributes
string $route_name
Detailed Description
Definition at line 12 of file GlobalPolicy.php.
Constructor & Destructor Documentation
__construct()
App\Policies\GlobalPolicy::__construct ($route_name)
Reimplemented in App\Policies\ApiLogPolicy, App\Policies\CrewPolicy, App\Policies\CytoscapePolicy, App\Policies\DuplicatePolicy, App\Policies\EventPolicy, App\Policies\FieldPolicy, App\Policies\LinkPolicy, App\Policies\ListControlPolicy, App\Policies\PermissionPolicy, App\Policies\RefugeePolicy, App\Policies\RolePolicy, App\Policies\SourcePolicy, and App\Policies\UserPolicy.
Definition at line 19 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\$route_name.
Member Function Documentation
create()
App\Policies\GlobalPolicy::create (User $user)
Determine whether the user can create models.
Parameters
User $user
Returns
Response|bool
Reimplemented in App\Policies\RefugeePolicy.
Definition at line 93 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
createFromJson()
App\Policies\GlobalPolicy::createFromJson (User $user)
Determine whether the user can create models using a Json
Parameters
User $user
Returns
Response|bool
Reimplemented in App\Policies\RefugeePolicy.
Definition at line 104 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
delete()
App\Policies\GlobalPolicy::delete (User $user, Model $model)
Determine whether the user can delete the model.
Parameters
User $user
Model $model
Returns
Response|bool
Reimplemented in App\Policies\FieldPolicy, and App\Policies\RolePolicy.
Definition at line 129 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
forceDelete()
App\Policies\GlobalPolicy::forceDelete (User $user, Model $model)
Determine whether the user can permanently delete the model.
Parameters
User $user
Model $model
Returns
Response|bool
Definition at line 155 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
hasPermission()
App\Policies\GlobalPolicy::hasPermission ($user, $function)
This function is user to check if a user has access to a route
Parameters
$user
$function
$route_name
Returns
boolean
Definition at line 42 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\$route_name.
Referenced by App\Policies\ListControlPolicy\addToList(), App\Policies\UserPolicy\changeTeam(), App\Policies\DuplicatePolicy\compute(), App\Policies\GlobalPolicy\create(), App\Policies\RefugeePolicy\create(), App\Policies\GlobalPolicy\createFromJson(), App\Policies\RefugeePolicy\createFromJson(), App\Policies\GlobalPolicy\delete(), App\Policies\RolePolicy\delete(), App\Policies\ListControlPolicy\deleteListElem(), App\Policies\GlobalPolicy\forceDelete(), App\Policies\UserPolicy\grantRole(), App\Policies\UserPolicy\invite(), App\Policies\UserPolicy\requestRole(), App\Policies\DuplicatePolicy\resolve(), App\Policies\GlobalPolicy\restore(), App\Policies\GlobalPolicy\update(), App\Policies\RolePolicy\update(), App\Policies\ListControlPolicy\updateListElem(), App\Policies\GlobalPolicy\view(), App\Policies\GlobalPolicy\viewAny(), and App\Policies\GlobalPolicy\viewMenu().
restore()
App\Policies\GlobalPolicy::restore (User $user, Model $model)
Determine whether the user can restore the model.
Parameters
User $user
Model $model
Returns
Response|bool
Definition at line 142 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
update()
App\Policies\GlobalPolicy::update (User $user, Model $model)
Determine whether the user can update the model.
Parameters
User $user
Model $model
Returns
Response|bool
Reimplemented in App\Policies\RolePolicy.
Definition at line 116 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
view()
App\Policies\GlobalPolicy::view (User $user, Model $model)
Determine whether the user can view the model.
Parameters
User $user
Model $model
Returns
Response|bool
Definition at line 81 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
viewAny()
App\Policies\GlobalPolicy::viewAny (User $user)
Determine whether the user can view any models.
Parameters
User $user
Returns
Response|bool
Definition at line 29 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
viewMenu()
App\Policies\GlobalPolicy::viewMenu (User $user)
Determine whether the user can view any models.
Parameters
User $user
Returns
Response|bool
Definition at line 62 of file GlobalPolicy.php.
References App\Policies\GlobalPolicy\hasPermission().
Member Data Documentation
$route_name
string App\Policies\GlobalPolicy::$route_name protected
Definition at line 17 of file GlobalPolicy.php.
Referenced by App\Policies\GlobalPolicy\__construct(), App\Policies\ApiLogPolicy\__construct(), App\Policies\CrewPolicy\__construct(), App\Policies\CytoscapePolicy\__construct(), App\Policies\DuplicatePolicy\__construct(), App\Policies\EventPolicy\__construct(), App\Policies\FieldPolicy\__construct(), App\Policies\LinkPolicy\__construct(), App\Policies\ListControlPolicy\__construct(), App\Policies\PermissionPolicy\__construct(), App\Policies\RefugeePolicy\__construct(), App\Policies\RolePolicy\__construct(), App\Policies\SourcePolicy\__construct(), App\Policies\UserPolicy\__construct(), and App\Policies\GlobalPolicy\hasPermission().
ERROR_MESSAGE
const App\Policies\GlobalPolicy::ERROR_MESSAGE = 'You do not have the right to do this.'
Definition at line 16 of file GlobalPolicy.php.
The documentation for this class was generated from the following file:
src/app/Policies/GlobalPolicy.php