SCAN: App\Models\Duplicate Class Reference
App\Models\Duplicate Class Reference
Public Member Functions
crew ()
person1 ()
person2 ()
commandRun ()
Static Public Member Functions
static nextID ($currentID)
static make_color ($value, $min=0, $max=1)
static compute (Crew $crew)
static isResolved (Refugee $person, Refugee $person2)
Public Attributes
$incrementing = false
Static Protected Member Functions
static hsl_to_rgb ($h, $s, $l)
Protected Attributes
$keyType = 'string'
$guarded = []
Detailed Description
Definition at line 11 of file Duplicate.php.
Member Function Documentation
commandRun()
App\Models\Duplicate::commandRun ()
Relation with command run
Returns
BelongsTo
Definition at line 267 of file Duplicate.php.
compute()
static App\Models\Duplicate::compute (Crew $crew) static
This function is used to get similar persons. It compares the similarity of the persons based on the fields that are completed. It computes the similarity of each field and then averages the similarity of each field to get the similarity of the persons for a given team. It must not compute the similarity of a person with itself. It must not compute the similarity of a person with a person that has already been compared. (eg A -> B is the same as B -> A) It must not compute the similarity of a couple that has already been compared and not edited since. It must not compute the similarity of a couple marked as "not similar" (ie resolve) by the user.
Parameters
Crew $crew
Definition at line 159 of file Duplicate.php.
References App\Models\Duplicate\isResolved(), App\Models\CommandRun\lastEnded(), and App\Models\Crew\persons().
Referenced by App\Console\Commands\DuplicateCommand\handle().
crew()
App\Models\Duplicate::crew ()
Relation with crew
Returns
BelongsTo
Definition at line 241 of file Duplicate.php.
hsl_to_rgb()
static App\Models\Duplicate::hsl_to_rgb ($h, $s, $l) static protected
Definition at line 91 of file Duplicate.php.
Referenced by App\Models\Duplicate\make_color().
isResolved()
static App\Models\Duplicate::isResolved (Refugee $person, Refugee $person2) static
This function is used to check if a couple of persons has been marked as "not similar" (ie resolve) by the user.
Parameters
Refugee $person
Refugee $person2
Returns
boolean
Definition at line 218 of file Duplicate.php.
Referenced by App\Models\Duplicate\compute().
make_color()
static App\Models\Duplicate::make_color ($value, $min = 0, $max = 1) static
Parameters
$value
integer | float $min
integer | float $max
Returns
string
Definition at line 61 of file Duplicate.php.
References App\Models\Duplicate\hsl_to_rgb().
nextID()
static App\Models\Duplicate::nextID ($currentID) static
Definition at line 40 of file Duplicate.php.
person1()
App\Models\Duplicate::person1 ()
Relation with person1
Returns
BelongsTo
Definition at line 249 of file Duplicate.php.
person2()
App\Models\Duplicate::person2 ()
Relation with person2
Returns
BelongsTo
Definition at line 258 of file Duplicate.php.
Member Data Documentation
$guarded
App\Models\Duplicate::$guarded = [] protected
Definition at line 37 of file Duplicate.php.
$incrementing
App\Models\Duplicate::$incrementing = false
Definition at line 21 of file Duplicate.php.
$keyType
App\Models\Duplicate::$keyType = 'string' protected
Definition at line 29 of file Duplicate.php.
The documentation for this class was generated from the following file:
src/app/Models/Duplicate.php