SCAN: App\Console\Commands\MakeList Class Reference
App\Console\Commands\MakeList Class Reference
Public Member Functions
__construct (Filesystem $files)
handle ()
Protected Attributes
$signature
$description = 'This command is used to create a new list.'
$files
Detailed Description
Definition at line 11 of file MakeList.php.
Constructor & Destructor Documentation
__construct()
App\Console\Commands\MakeList::__construct (Filesystem $files)
Create a new command instance.
Parameters
Filesystem $files
Definition at line 43 of file MakeList.php.
References App\Console\Commands\MakeList\$files.
Member Function Documentation
handle()
App\Console\Commands\MakeList::handle ()
Definition at line 52 of file MakeList.php.
References App\Console\Commands\MakeCommandSet\getSourceFilePath(), App\Console\Commands\MakeCommandSet\getStubContents(), and App\Console\Commands\MakeCommandSet\getStubPath().
Member Data Documentation
$description
App\Console\Commands\MakeList::$description = 'This command is used to create a new list.' protected
Definition at line 26 of file MakeList.php.
$files
App\Console\Commands\MakeList::$files protected
Definition at line 37 of file MakeList.php.
Referenced by App\Console\Commands\MakeList\__construct().
$signature
App\Console\Commands\MakeList::$signature protected
Initial value:
= 'make:list
                            {id : The id of the list to create (this id should exists in ListControl table}'
Definition at line 18 of file MakeList.php.
The documentation for this class was generated from the following file:
src/app/Console/Commands/MakeList.php