SCAN: App\Actions\Jetstream\AddTeamMember Class Reference
App\Actions\Jetstream\AddTeamMember Class Reference
Public Member Functions
add ($user, $team, string $email, string $role=null)
Protected Member Functions
validate ($team, string $email, ?string $role)
rules ()
ensureUserIsNotAlreadyOnTeam ($team, string $email)
Detailed Description
Definition at line 13 of file AddTeamMember.php.
Member Function Documentation
add()
App\Actions\Jetstream\AddTeamMember::add ($user, $team, string $email, string $role = null)
Add a new team member to the given team.
Parameters
mixed $user
mixed $team
string $email
string | null $role
Returns
void
Definition at line 24 of file AddTeamMember.php.
References App\Actions\Jetstream\AddTeamMember\validate().
ensureUserIsNotAlreadyOnTeam()
App\Actions\Jetstream\AddTeamMember::ensureUserIsNotAlreadyOnTeam ($team, string $email) protected
Ensure that the user is not already on the team.
Parameters
mixed $team
string $email
Returns
\Closure
Definition at line 83 of file AddTeamMember.php.
Referenced by App\Actions\Jetstream\AddTeamMember\validate().
rules()
App\Actions\Jetstream\AddTeamMember::rules () protected
Get the validation rules for adding a team member.
Returns
array
Definition at line 66 of file AddTeamMember.php.
Referenced by App\Actions\Jetstream\AddTeamMember\validate().
validate()
App\Actions\Jetstream\AddTeamMember::validate ($team, string $email, ?string $role) protected
Validate the add member operation.
Parameters
mixed $team
string $email
string | null $role
Returns
void
Definition at line 49 of file AddTeamMember.php.
References App\Actions\Jetstream\AddTeamMember\ensureUserIsNotAlreadyOnTeam(), and App\Actions\Jetstream\AddTeamMember\rules().
Referenced by App\Actions\Jetstream\AddTeamMember\add().
The documentation for this class was generated from the following file:
src/app/Actions/Jetstream/AddTeamMember.php