SCAN: App\Models\ListControl Class Reference
App\Models\ListControl Class Reference
Public Member Functions
fields ()
list_content ()
crews ()
getListDisplayedValue ()
getListContent ()
getListFields ()
getDisplayedValueAttribute ()
structure ()
associatedStructureFields ()
getDisplayedValueContentAttribute ()
findElement ($field, $value)
Static Public Member Functions
static getDisplayedValueContent ($id)
static getIdFromValue ($value)
static getAPIContent (User $user)
static list ()
static getDisplayedValue ()
static getListFromLinkedListName ($list_name)
static getListFromLinkedListId ($id)
static getListElementFromId ($list_id, $element_id)
static getDisplayedValueFromListName ()
Public Attributes
$incrementing = false
Protected Attributes
$keyType = 'string'
$guarded = []
$hidden
Detailed Description
Definition at line 12 of file ListControl.php.
Member Function Documentation
associatedStructureFields()
App\Models\ListControl::associatedStructureFields ()
TODO : rename this function when using the associative table with fields
Returns
void
Definition at line 225 of file ListControl.php.
crews()
App\Models\ListControl::crews ()
Definition at line 182 of file ListControl.php.
fields()
App\Models\ListControl::fields ()
Definition at line 172 of file ListControl.php.
findElement()
App\Models\ListControl::findElement ($field, $value)
This function finds the element in the list, based on field, value
Parameters
string $field
string $value
Returns
object | null
Definition at line 253 of file ListControl.php.
getAPIContent()
static App\Models\ListControl::getAPIContent (User $user) static
It returns the list control dataset for API calls
Returns
array
Definition at line 94 of file ListControl.php.
getDisplayedValue()
static App\Models\ListControl::getDisplayedValue () static
Definition at line 132 of file ListControl.php.
Referenced by App\Models\ListControl\list().
getDisplayedValueAttribute()
App\Models\ListControl::getDisplayedValueAttribute ()
Definition at line 211 of file ListControl.php.
References App\Models\ListControl\structure().
getDisplayedValueContent()
static App\Models\ListControl::getDisplayedValueContent ($id) static
It returns the content of the displayed value of the control list
Parameters
$id
Returns
string
Definition at line 54 of file ListControl.php.
getDisplayedValueContentAttribute()
App\Models\ListControl::getDisplayedValueContentAttribute ()
Definition at line 231 of file ListControl.php.
References App\Models\ListControl\getDisplayedValueFromListName().
getDisplayedValueFromListName()
static App\Models\ListControl::getDisplayedValueFromListName () static
This function returns the displayed value of the list from the list name
Definition at line 238 of file ListControl.php.
Referenced by App\Models\ListControl\getDisplayedValueContentAttribute().
getIdFromValue()
static App\Models\ListControl::getIdFromValue ($value) static
Definition at line 67 of file ListControl.php.
Referenced by App\Models\Link\relationExists().
getListContent()
App\Models\ListControl::getListContent ()
Definition at line 192 of file ListControl.php.
Referenced by App\Http\Controllers\ListControlController\apiGetList(), App\Models\ListControl\getListDisplayedValue(), and App\Http\Controllers\ListControlController\show().
getListDisplayedValue()
App\Models\ListControl::getListDisplayedValue ()
Definition at line 188 of file ListControl.php.
References App\Models\ListControl\getListContent().
getListElementFromId()
static App\Models\ListControl::getListElementFromId ($list_id, $element_id) static
This function get a list element from :
the list id
the element id
Parameters
string $list_id
string $element_id
Definition at line 165 of file ListControl.php.
Referenced by App\Models\Refugee\formatRefugeesData().
getListFields()
App\Models\ListControl::getListFields ()
This function returns the fields that describes the list (± the table columns) e.g : Country is described by ISO2, ISO3, full_name
Definition at line 204 of file ListControl.php.
getListFromLinkedListId()
static App\Models\ListControl::getListFromLinkedListId ($id) static
This function get the list from the list id
Definition at line 153 of file ListControl.php.
getListFromLinkedListName()
static App\Models\ListControl::getListFromLinkedListName ($list_name) static
This function get the list from the list name
Definition at line 145 of file ListControl.php.
list()
static App\Models\ListControl::list () static
Definition at line 123 of file ListControl.php.
References App\Models\ListControl\getDisplayedValue().
list_content()
App\Models\ListControl::list_content ()
Definition at line 177 of file ListControl.php.
structure()
App\Models\ListControl::structure ()
Definition at line 215 of file ListControl.php.
Referenced by App\Http\Controllers\ListControlController\addToList(), App\Http\Controllers\ListControlController\editListElem(), App\Models\ListControl\getDisplayedValueAttribute(), App\Http\Controllers\ListControlController\show(), and App\Http\Controllers\ListControlController\storeFields().
Member Data Documentation
$guarded
App\Models\ListControl::$guarded = [] protected
Definition at line 34 of file ListControl.php.
$hidden
App\Models\ListControl::$hidden protected
Initial value:
= [
        'deleted_at',
        "created_at",
        "updated_at",
    ]
Definition at line 41 of file ListControl.php.
$incrementing
App\Models\ListControl::$incrementing = false
Definition at line 22 of file ListControl.php.
$keyType
App\Models\ListControl::$keyType = 'string' protected
Definition at line 28 of file ListControl.php.
The documentation for this class was generated from the following file:
src/app/Models/ListControl.php