SCAN: App\Console\Commands\MakeCommandSet Class Reference
App\Console\Commands\MakeCommandSet Class Reference
Static Public Member Functions
static getSourceFilePath ($path, $name)
static getStubContents ($stub, $stubVariables=[])
static getStubPath ($name)
Detailed Description
Definition at line 5 of file MakeCommandSet.php.
Member Function Documentation
getSourceFilePath()
static App\Console\Commands\MakeCommandSet::getSourceFilePath ($path, $name) static
Get the full path of generate class
Returns
string
Definition at line 14 of file MakeCommandSet.php.
Referenced by App\Console\Commands\MakeList\handle(), and App\Console\Commands\MakeResourceTest\handle().
getStubContents()
static App\Console\Commands\MakeCommandSet::getStubContents ($stub, $stubVariables = []) static
Replace the stub variables(key) with the desire value
Parameters
$stub
array $stubVariables
Returns
bool|mixed|string
Definition at line 28 of file MakeCommandSet.php.
Referenced by App\Console\Commands\MakeList\handle(), and App\Console\Commands\MakeResourceTest\handle().
getStubPath()
static App\Console\Commands\MakeCommandSet::getStubPath ($name) static
Return the stub file path
Returns
string
Definition at line 47 of file MakeCommandSet.php.
Referenced by App\Console\Commands\MakeList\handle(), and App\Console\Commands\MakeResourceTest\handle().
The documentation for this class was generated from the following file:
src/app/Console/Commands/MakeCommandSet.php