SCAN: App\Http\Controllers\ListControlController Class Reference
App\Http\Controllers\ListControlController Class Reference
Public Member Functions
__construct ()
index ()
addToList (ListControl $list_control)
updateList (StoreUpdateListRequest $request, ListControl $listControl)
create ()
editListElem (ListControl $listControl, $element)
updateListElem (UpdateListElemRequest $request, ListControl $listControl, $element)
update (UpdateListControlRequest $request, ListControl $lists_control)
store (StoreListControlRequest $request)
createFields (ListControl $listControl)
storeFields (StoreListControlFieldsRequest $request, ListControl $listControl)
storeDisplayedValue (StoreListControlAddDisplayedValue $request, ListControl $listControl)
show (ListControl $lists_control)
edit (ListControl $lists_control)
destroy (ListControl $lists_control)
destroyListElem (ListControl $listControl, $element)
apiGetLists (Request $request)
apiGetList (Request $request, ListControl $listControl)
Detailed Description
Definition at line 23 of file ListControlController.php.
Constructor & Destructor Documentation
__construct()
App\Http\Controllers\ListControlController::__construct ()
Create the controller instance.
Returns
void
Definition at line 30 of file ListControlController.php.
Member Function Documentation
addToList()
App\Http\Controllers\ListControlController::addToList (ListControl $list_control)
This function is used to add an element to an existing list
Parameters
ListControl $list_control
Returns
View
Definition at line 58 of file ListControlController.php.
References App\Models\ListControl\structure().
apiGetList()
App\Http\Controllers\ListControlController::apiGetList (Request $request, ListControl $listControl)
This function returns the content of a list to the API
Parameters
Request $request
ListControl $listControl
Returns
JsonResponse
Definition at line 302 of file ListControlController.php.
References App\Models\ListControl\getListContent().
apiGetLists()
App\Http\Controllers\ListControlController::apiGetLists (Request $request)
This function returns the lists of all the lists to the API
Parameters
Request $request
Returns
JsonResponse
Definition at line 283 of file ListControlController.php.
create()
App\Http\Controllers\ListControlController::create ()
Show the form for creating a new resource.
Returns
View
Definition at line 90 of file ListControlController.php.
createFields()
App\Http\Controllers\ListControlController::createFields (ListControl $listControl)
Definition at line 170 of file ListControlController.php.
destroy()
App\Http\Controllers\ListControlController::destroy (ListControl $lists_control)
Remove the specified resource from storage.
Parameters
ListControl $lists_control
Returns
RedirectResponse
Definition at line 249 of file ListControlController.php.
destroyListElem()
App\Http\Controllers\ListControlController::destroyListElem (ListControl $listControl, $element)
Remove the specified resource from storage.
Parameters
ListControl $lists_control
$element
Returns
RedirectResponse
Definition at line 265 of file ListControlController.php.
edit()
App\Http\Controllers\ListControlController::edit (ListControl $lists_control)
Show the form for editing the specified resource.
Parameters
ListControl $lists_control
Returns
View
Definition at line 238 of file ListControlController.php.
editListElem()
App\Http\Controllers\ListControlController::editListElem (ListControl $listControl, $element)
This function is used to add an element to a list
Parameters
ListControl $listControl
$element
Returns
View
Definition at line 102 of file ListControlController.php.
References App\Models\ListControl\structure().
index()
App\Http\Controllers\ListControlController::index ()
Display a listing of the resource.
Returns
View
Definition at line 40 of file ListControlController.php.
show()
App\Http\Controllers\ListControlController::show (ListControl $lists_control)
Display the specified resource.
Parameters
ListControl $lists_control
Returns
View
Definition at line 225 of file ListControlController.php.
References App\Models\ListControl\getListContent(), and App\Models\ListControl\structure().
store()
App\Http\Controllers\ListControlController::store (StoreListControlRequest $request)
Store a newly created resource in storage.
Parameters
StoreListControlRequest $request
Returns
View
Definition at line 155 of file ListControlController.php.
storeDisplayedValue()
App\Http\Controllers\ListControlController::storeDisplayedValue (StoreListControlAddDisplayedValue $request, ListControl $listControl)
Store the displayed value
Parameters
StoreListControlAddDisplayedValue $request
Returns
RedirectResponse
Definition at line 211 of file ListControlController.php.
storeFields()
App\Http\Controllers\ListControlController::storeFields (StoreListControlFieldsRequest $request, ListControl $listControl)
After creating the list, this controller method is called to store the fields which describes the list
Parameters
StoreListControlFieldsRequest $request
Returns
RedirectResponse
Definition at line 182 of file ListControlController.php.
References App\Models\ListControl\structure().
update()
App\Http\Controllers\ListControlController::update (UpdateListControlRequest $request, ListControl $lists_control)
Update the specified resource in storage.
Parameters
UpdateListControlRequest $request
ListControl $lists_control
Returns
RedirectResponse
Definition at line 143 of file ListControlController.php.
updateList()
App\Http\Controllers\ListControlController::updateList (StoreUpdateListRequest $request, ListControl $listControl)
This function is used to add an element to a list
Parameters
StoreUpdateListRequest $request
ListControl $listControl
Returns
View
Definition at line 73 of file ListControlController.php.
updateListElem()
App\Http\Controllers\ListControlController::updateListElem (UpdateListElemRequest $request, ListControl $listControl, $element)
This function is used to add an element to a list
Parameters
UpdateListElemRequest $request
ListControl $listControl
$element
Returns
View
Definition at line 121 of file ListControlController.php.
The documentation for this class was generated from the following file:
src/app/Http/Controllers/ListControlController.php