SCAN: App\Models\Crew Class Reference
App\Models\Crew Class Reference
Public Member Functions
users ()
persons ()
relations ()
hasEvent ()
fields ()
Static Public Member Functions
static getDefaultCrewId ()
Public Attributes
$incrementing = false
Protected Attributes
$keyType = 'string'
$guarded = []
Detailed Description
Definition at line 10 of file Crew.php.
Member Function Documentation
fields()
App\Models\Crew::fields ()
Definition at line 68 of file Crew.php.
Referenced by App\Models\Crew\hasEvent().
getDefaultCrewId()
static App\Models\Crew::getDefaultCrewId () static
Definition at line 34 of file Crew.php.
Referenced by App\Models\User\createDefaultUser().
hasEvent()
App\Models\Crew::hasEvent ()
Definition at line 63 of file Crew.php.
References App\Models\Crew\fields().
persons()
App\Models\Crew::persons ()
Definition at line 47 of file Crew.php.
Referenced by App\Models\Duplicate\compute().
relations()
App\Models\Crew::relations ()
Definition at line 55 of file Crew.php.
users()
App\Models\Crew::users ()
Definition at line 43 of file Crew.php.
Referenced by App\Http\Controllers\CrewController\destroy(), and App\Http\Controllers\CrewController\show().
Member Data Documentation
$guarded
App\Models\Crew::$guarded = [] protected
Definition at line 32 of file Crew.php.
$incrementing
App\Models\Crew::$incrementing = false
Definition at line 20 of file Crew.php.
$keyType
App\Models\Crew::$keyType = 'string' protected
Definition at line 26 of file Crew.php.
The documentation for this class was generated from the following file:
src/app/Models/Crew.php