SCAN: App\Models\Refugee Class Reference
App\Models\Refugee Class Reference
Public Member Functions
user ()
fields ()
allCoordinates ()
toRelation ()
fromRelation ()
crew ()
getRepresentativeValuesAttribute ()
getBestDescriptiveValueAttribute ()
getRelationsAttribute ()
hasEvent ()
getEventAttribute ()
Static Public Member Functions
static getAllBestDescriptiveValues ()
static handleApiRequest ($person)
static formatRefugeesData ($refugees)
Public Attributes
const route_base = "person"
$incrementing = false
Static Protected Member Functions
static boot ()
Protected Attributes
$keyType = 'string'
$guarded = []
Detailed Description
Definition at line 15 of file Refugee.php.
Member Function Documentation
allCoordinates()
App\Models\Refugee::allCoordinates ()
Definition at line 186 of file Refugee.php.
References App\Models\Refugee\fields().
Referenced by App\Http\Controllers\RefugeeController\show().
boot()
static App\Models\Refugee::boot () static protected
Definition at line 229 of file Refugee.php.
crew()
App\Models\Refugee::crew ()
The crew to which the refugee is associated.
Definition at line 259 of file Refugee.php.
Referenced by App\Models\Refugee\fields().
fields()
App\Models\Refugee::fields ()
The fields that describe the user.
Definition at line 180 of file Refugee.php.
References App\Models\Refugee\crew().
Referenced by App\Models\Refugee\allCoordinates(), App\Http\Controllers\RefugeeController\edit(), and App\Http\Controllers\RefugeeController\update().
formatRefugeesData()
static App\Models\Refugee::formatRefugeesData ($refugees) static
This function is used to format refugees' data. It takes a collection of refugees and returns an array of formatted refugees data. Here is the format of the returned array: [ "refugee_id" => [ "unique_id" => "refugee_unique_id", "gender" => "Male", "age" => 25, ... ], ... ]
Parameters
$refugees
Returns
array
Definition at line 206 of file Refugee.php.
References App\Models\ListControl\getListElementFromId().
fromRelation()
App\Models\Refugee::fromRelation ()
Definition at line 250 of file Refugee.php.
getAllBestDescriptiveValues()
static App\Models\Refugee::getAllBestDescriptiveValues () static
Definition at line 44 of file Refugee.php.
getBestDescriptiveValueAttribute()
App\Models\Refugee::getBestDescriptiveValueAttribute ()
Definition at line 272 of file Refugee.php.
getEventAttribute()
App\Models\Refugee::getEventAttribute ()
Definition at line 293 of file Refugee.php.
getRelationsAttribute()
App\Models\Refugee::getRelationsAttribute ()
Definition at line 281 of file Refugee.php.
getRepresentativeValuesAttribute()
App\Models\Refugee::getRepresentativeValuesAttribute ()
Definition at line 267 of file Refugee.php.
handleApiRequest()
static App\Models\Refugee::handleApiRequest ($person) static
The Api log to which the refugee is associated. This function is used to handle the API request. If a person exists (id is in the request) update all changed fields, else create the person and return his/her ID.
Parameters
$person
Returns
Application|ResponseFactory|\Illuminate\Http\Response|null
Definition at line 91 of file Refugee.php.
hasEvent()
App\Models\Refugee::hasEvent ()
Definition at line 288 of file Refugee.php.
toRelation()
App\Models\Refugee::toRelation ()
Definition at line 244 of file Refugee.php.
user()
App\Models\Refugee::user ()
The user to which the refugee is associated.
Definition at line 57 of file Refugee.php.
Member Data Documentation
$guarded
App\Models\Refugee::$guarded = [] protected
Definition at line 42 of file Refugee.php.
$incrementing
App\Models\Refugee::$incrementing = false
Definition at line 30 of file Refugee.php.
$keyType
App\Models\Refugee::$keyType = 'string' protected
Definition at line 36 of file Refugee.php.
route_base
const App\Models\Refugee::route_base = "person"
Definition at line 23 of file Refugee.php.
The documentation for this class was generated from the following file:
src/app/Models/Refugee.php