SCAN: App\Console\Commands\MakeResourceTest Class Reference
App\Console\Commands\MakeResourceTest Class Reference
Public Member Functions
__construct (Filesystem $files)
handle ()
Protected Attributes
$signature = 'make:resourceTest {route} {model}'
$description
$files
Detailed Description
Definition at line 8 of file MakeResourceTest.php.
Constructor & Destructor Documentation
__construct()
App\Console\Commands\MakeResourceTest::__construct (Filesystem $files)
Create a new command instance.
Parameters
Filesystem $files
Definition at line 39 of file MakeResourceTest.php.
References App\Console\Commands\MakeResourceTest\$files.
Member Function Documentation
handle()
App\Console\Commands\MakeResourceTest::handle ()
Execute the console command.
Returns
int
Definition at line 52 of file MakeResourceTest.php.
References App\Console\Commands\MakeCommandSet\getSourceFilePath(), App\Console\Commands\MakeCommandSet\getStubContents(), and App\Console\Commands\MakeCommandSet\getStubPath().
Member Data Documentation
$description
App\Console\Commands\MakeResourceTest::$description protected
Initial value:
= 'This command will create a resource test file for the given model.
    The file will be created in the tests/Feature folder.
    The test will check that the user can access the page and
    that the user can\'t access the page if he doesn\'t have the permission.
    Checked permissions are: *.index, *.show, *.create, *.edit, *.destroy.
    It will also check that the user can\'t access the page if he is not authenticated.'
Definition at line 22 of file MakeResourceTest.php.
$files
App\Console\Commands\MakeResourceTest::$files protected
Definition at line 33 of file MakeResourceTest.php.
Referenced by App\Console\Commands\MakeResourceTest\__construct().
$signature
App\Console\Commands\MakeResourceTest::$signature = 'make:resourceTest {route} {model}' protected
Definition at line 16 of file MakeResourceTest.php.
The documentation for this class was generated from the following file:
src/app/Console/Commands/MakeResourceTest.php