SCAN: App\Models\Link Class Reference
App\Models\Link Class Reference
Public Member Functions
getBestDescriptiveValueAttribute ()
refugeeFrom ()
refugeeTo ()
relation ()
crew ()
getFromId ()
getToId ()
getRelationWeight ()
getRelationId ()
getDateAttribute ()
Static Public Member Functions
static handleApiRequest ($relation)
static relationExists ($from, $to, $relation_type, $application_id)
Public Attributes
const route_base = "links"
$incrementing = false
Static Public Attributes
static bool $quickAdd = true
Protected Attributes
$table = "links"
$keyType = 'string'
$fillable = ["from", "to", "relation_id", "date", "detail", 'api_log']
$encryptable
Detailed Description
Definition at line 14 of file Link.php.
Member Function Documentation
crew()
App\Models\Link::crew ()
Definition at line 132 of file Link.php.
getBestDescriptiveValueAttribute()
App\Models\Link::getBestDescriptiveValueAttribute ()
It returns a representative value, witch could be shown to discribe the element
Returns
mixed
Definition at line 111 of file Link.php.
References App\Models\Link\refugeeFrom(), and App\Models\Link\refugeeTo().
getDateAttribute()
App\Models\Link::getDateAttribute ()
Store the relation id accorting its key or its code
Parameters
$value
Definition at line 182 of file Link.php.
getFromId()
App\Models\Link::getFromId ()
Get from Id
Returns
mixed
Definition at line 146 of file Link.php.
getRelationId()
App\Models\Link::getRelationId ()
Get relation name
Parameters
$relation
Returns
mixed
Definition at line 169 of file Link.php.
Referenced by App\Models\Link\getRelationWeight().
getRelationWeight()
App\Models\Link::getRelationWeight ()
Definition at line 158 of file Link.php.
References App\Models\Link\getRelationId().
getToId()
App\Models\Link::getToId ()
Get to Id
Returns
mixed
Definition at line 154 of file Link.php.
handleApiRequest()
static App\Models\Link::handleApiRequest ($relation) static
Definition at line 62 of file Link.php.
refugeeFrom()
App\Models\Link::refugeeFrom ()
Definition at line 115 of file Link.php.
Referenced by App\Models\Link\getBestDescriptiveValueAttribute().
refugeeTo()
App\Models\Link::refugeeTo ()
Definition at line 120 of file Link.php.
Referenced by App\Models\Link\getBestDescriptiveValueAttribute().
relation()
App\Models\Link::relation ()
Returns
BelongsTo
Definition at line 128 of file Link.php.
Referenced by App\Http\Controllers\LinkController\edit().
relationExists()
static App\Models\Link::relationExists ($from, $to, $relation_type, $application_id) static
Definition at line 94 of file Link.php.
References App\Models\ListControl\getIdFromValue().
Member Data Documentation
$encryptable
App\Models\Link::$encryptable protected
Initial value:
= [
    ]
Definition at line 59 of file Link.php.
$fillable
App\Models\Link::$fillable = ["from", "to", "relation_id", "date", "detail", 'api_log'] protected
Definition at line 52 of file Link.php.
$incrementing
App\Models\Link::$incrementing = false
Definition at line 35 of file Link.php.
$keyType
App\Models\Link::$keyType = 'string' protected
Definition at line 46 of file Link.php.
$quickAdd
bool App\Models\Link::$quickAdd = true static
Definition at line 28 of file Link.php.
$table
App\Models\Link::$table = "links" protected
Table
Definition at line 40 of file Link.php.
route_base
const App\Models\Link::route_base = "links"
Definition at line 22 of file Link.php.
The documentation for this class was generated from the following file:
src/app/Models/Link.php