SCAN: App\Models\Translation Class Reference
App\Models\Translation Class Reference
Public Member Functions
getLanguageAttribute ($value)
autoTranslate ()
Static Public Member Functions
static handleTranslation (ListControl $listControl, $element, $content, $language="default")
Public Attributes
$incrementing = false
Protected Attributes
$keyType = 'string'
$hidden = ['deleted_at', "created_at", "updated_at"]
$guarded = []
Detailed Description
Definition at line 11 of file Translation.php.
Member Function Documentation
autoTranslate()
App\Models\Translation::autoTranslate ()
This function is used to translate with deepl
Definition at line 58 of file Translation.php.
References $response, App\Models\Translation\handleTranslation(), and App\Models\Language\otherLanguages().
getLanguageAttribute()
App\Models\Translation::getLanguageAttribute ($value)
Return ISO3 language name
Parameters
$value
Returns
mixed
Definition at line 50 of file Translation.php.
handleTranslation()
static App\Models\Translation::handleTranslation (ListControl $listControl, $element, $content, $language = "default") static
Definition at line 74 of file Translation.php.
References App\Models\Language\defaultLanguage().
Referenced by App\Models\Translation\autoTranslate().
Member Data Documentation
$guarded
App\Models\Translation::$guarded = [] protected
Definition at line 42 of file Translation.php.
$hidden
App\Models\Translation::$hidden = ['deleted_at', "created_at", "updated_at"] protected
Definition at line 35 of file Translation.php.
$incrementing
App\Models\Translation::$incrementing = false
Definition at line 27 of file Translation.php.
$keyType
App\Models\Translation::$keyType = 'string' protected
Definition at line 19 of file Translation.php.
The documentation for this class was generated from the following file:
src/app/Models/Translation.php