SCAN: Database\Seeders\GlobalListControlSeeder Class Reference
Database\Seeders\GlobalListControlSeeder Class Reference
Public Member Functions
__construct ($list_name)
run ()
Protected Member Functions
getJsonDatas ()
getListInfo ()
storeTranslation ($displayed_value, $field_key)
Protected Attributes
$list_name
$class_name
$array_json
$displayed_value
$list_id
$languages
$default_language
$list_field_key
$list
Detailed Description
Definition at line 11 of file GlobalListControlSeeder.php.
Constructor & Destructor Documentation
__construct()
Database\Seeders\GlobalListControlSeeder::__construct ($list_name)
GlobalListControlSeeder constructor.
Parameters
$list_name
Definition at line 27 of file GlobalListControlSeeder.php.
References Database\Seeders\GlobalListControlSeeder\$list_name, Database\Seeders\GlobalListControlSeeder\getJsonDatas(), and Database\Seeders\GlobalListControlSeeder\getListInfo().
Member Function Documentation
getJsonDatas()
Database\Seeders\GlobalListControlSeeder::getJsonDatas () protected
Initialize the json_array from json file
Parameters
$json_name
Definition at line 44 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\GlobalListControlSeeder\__construct().
getListInfo()
Database\Seeders\GlobalListControlSeeder::getListInfo () protected
Definition at line 49 of file GlobalListControlSeeder.php.
References Database\Seeders\GlobalListControlSeeder\$list.
Referenced by Database\Seeders\GlobalListControlSeeder\__construct().
run()
Database\Seeders\GlobalListControlSeeder::run ()
Run the database seeds.
Returns
void
Reimplemented in Database\Seeders\FieldSeeder.
Definition at line 62 of file GlobalListControlSeeder.php.
References Database\Seeders\GlobalListControlSeeder\$class_name, Database\Seeders\GlobalListControlSeeder\$default_language, and Database\Seeders\GlobalListControlSeeder\storeTranslation().
storeTranslation()
Database\Seeders\GlobalListControlSeeder::storeTranslation ($displayed_value, $field_key) protected
Definition at line 89 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\FieldSeeder\run(), and Database\Seeders\GlobalListControlSeeder\run().
Member Data Documentation
$array_json
Database\Seeders\GlobalListControlSeeder::$array_json protected
Definition at line 15 of file GlobalListControlSeeder.php.
$class_name
Database\Seeders\GlobalListControlSeeder::$class_name protected
Definition at line 14 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\GlobalListControlSeeder\run().
$default_language
Database\Seeders\GlobalListControlSeeder::$default_language protected
Definition at line 19 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\FieldSeeder\run(), and Database\Seeders\GlobalListControlSeeder\run().
$displayed_value
Database\Seeders\GlobalListControlSeeder::$displayed_value protected
Definition at line 16 of file GlobalListControlSeeder.php.
$languages
Database\Seeders\GlobalListControlSeeder::$languages protected
Definition at line 18 of file GlobalListControlSeeder.php.
$list
Database\Seeders\GlobalListControlSeeder::$list protected
Definition at line 21 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\GlobalListControlSeeder\getListInfo().
$list_field_key
Database\Seeders\GlobalListControlSeeder::$list_field_key protected
Definition at line 20 of file GlobalListControlSeeder.php.
$list_id
Database\Seeders\GlobalListControlSeeder::$list_id protected
Definition at line 17 of file GlobalListControlSeeder.php.
$list_name
Database\Seeders\GlobalListControlSeeder::$list_name protected
Definition at line 13 of file GlobalListControlSeeder.php.
Referenced by Database\Seeders\GlobalListControlSeeder\__construct().
The documentation for this class was generated from the following file:
src/database/seeders/GlobalListControlSeeder.php