SCAN: src/public/deploy.php File Reference
deploy.php File Reference
Variables
$TITLE = 'Git Auto deployment - beta'
$VERSION = '0.11'
echo; $allowed_ips=array("192.30.252.", "185.199.108.", "140.82.112.", "143.55.64.", "2a0a:a440::", "2606:50c0::"); $allowed=false; $headers=apache_request_headers();if(@ $headers["X-Forwarded-For"]) { $ips=explode(",", $headers["X-Forwarded-For"]);$ip=$ips[0];} else { $ip=$_SERVER[ 'REMOTE_ADDR'];}foreach($allowed_ips as $allow) { if(stripos($ip, $allow) !==false) { $allowed=true;break;}}if(! $allowed) { header('HTTP/1.1 403 Forbidden');echo "<span style=\"color: #ff0000\"> Sorry
echo;$allowed_ips=array("192.30.252.", "185.199.108.", "140.82.112.", "143.55.64.", "2a0a:a440::", "2606:50c0::");$allowed=false;$headers=apache_request_headers();if(@ $headers["X-Forwarded-For"]) { $ips=explode(",", $headers["X-Forwarded-For"]);$ip=$ips[0];} else { $ip=$_SERVER['REMOTE_ADDR'];}foreach($allowed_ips as $allow) { if(stripos($ip, $allow) !==false) { $allowed=true;break;}}if(! $allowed) { header('HTTP/1.1 403 Forbidden');echo "<span style=\"color: #ff0000\"> no hamster better convince your parents</span> n</pre> n</body> n</html> n foreach ($commands as $command) $log = "\n"
Variable Documentation
$log
echo; $allowed_ips=array("192.30.252.", "185.199.108.", "140.82.112.", "143.55.64.", "2a0a:a440::", "2606:50c0::"); $allowed=false; $headers=apache_request_headers();if(@ $headers["X-Forwarded-For"]) { $ips=explode(",", $headers["X-Forwarded-For"]); $ip=$ips[0];} else { $ip=$_SERVER[ 'REMOTE_ADDR'];}foreach($allowed_ips as $allow) { if(stripos($ip, $allow) !==false) { $allowed=true; break; }}if(! $allowed) { header('HTTP/1.1 403 Forbidden'); echo "<span style=\"color: #ff0000\"> no hamster better convince your parents</span> n</pre> n</body> n</html> n foreach ($commands as $command) $log = "\n"
Definition at line 85 of file deploy.php.
Referenced by App\Http\Controllers\RefugeeController\apiGetPerson(), App\Imports\RefugeesImport\collection(), App\Models\ApiLog\createFromRequest(), Database\Factories\EventFactory\definition(), Database\Factories\LinkFactory\definition(), Database\Factories\RefugeeFactory\definition(), App\Http\Controllers\FieldsController\handleApiRequest(), App\Http\Controllers\LinkController\handleApiRequest(), App\Http\Controllers\RefugeeController\handleApiRequest(), Database\Seeders\FieldSeeder\run(), App\Http\Controllers\EventController\store(), App\Http\Controllers\RefugeeController\store(), App\Http\Controllers\LinkController\storeFromJson(), App\Http\Controllers\RefugeeController\storeFromJson(), App\Http\Controllers\LinkController\update(), and App\Http\Controllers\RefugeeController\update().
$TITLE
$TITLE = 'Git Auto deployment - beta'
Definition at line 7 of file deploy.php.
$VERSION
$VERSION = '0.11'
Definition at line 8 of file deploy.php.
Sorry
echo;$allowed_ips = array("192.30.252.", "185.199.108.", "140.82.112.", "143.55.64.", "2a0a:a440::", "2606:50c0::");$allowed = false;$headers = apache_request_headers();if (@$headers["X-Forwarded-For"]) { $ips = explode(",", $headers["X-Forwarded-For"]); $ip = $ips[0];} else { $ip = $_SERVER['REMOTE_ADDR'];}foreach ($allowed_ips as $allow) { if (stripos($ip, $allow) !== false) { $allowed = true; break; }}if (!$allowed) { header('HTTP/1.1 403 Forbidden'); echo "<span style=\"color: #ff0000\"> Sorry
Definition at line 55 of file deploy.php.